### ISSUE TITLE
More Saps Parameters

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/gym-parameter-control#3]
Currently I'm not sure which other parameters would be nice. Maybe there is a restart parameter we could control

**Comment by AndreBiedenkapp** [comment]
➤ André Biedenkapp commented:

This involves more than just identifying interesting parameters and specifying a pcs. For this the RSAPS code needs to be modified to allow for changes to different parameters.

**Comment by hfurkanbozkurt** [comment]
Max-delta parameter is exposed.
